Mock dns resolving and speedup tests
py-mine/mcstatus pull request #347
Opened 2022-07-05 17:23 UTC by PerchunPak

If old time was ~5s on running all tests, now I have ~0.7s on all this.

2022-07-05 19:22 UTC, kevinkjt2000 requested changes
Thanks for another contribution! One change request before I approve.

2022-07-05 20:56 UTC, PerchunPak commented on mcstatus/tests/test_server.py
> +                        self.server.query()
Thanks for the tip, I implemented it in https://github.com/py-mine/mcstatus/pull/347/commits/a4c195b02980f87e31bd6dacb02bbb3a926d1399.

2022-07-06 15:42 UTC, PerchunPak commented
P.S. This also allows run tests without internet, and on Termux (which cannot resolve DNS, because of it's own reasons).

2022-07-12 00:40 UTC, kevinkjt2000 approved these changes

2022-07-12 00:40 UTC, merged